### ISSUE TITLE
OSC-Platform: Migrate services currently hosted on Operate First platform to OS-Climate managed clusters

### ISSUE THREAD

**Issue by redmikhail** [os-climate/os_c_data_commons#270]
Operate First community is considering restructuring some of platforms that host services consumed by OS-Climate for managing clusters and applications. To avoid adverse impact on availability and stability of OSC data commons  platform affected services needs to be migrated to internally managed clusters. Following services currently hosted on Operate First owned infrastructure: 

- [x] RH Advanced Cluster Management - OSC clusters are integrated as managed clusters however outside of provisioning ArgoCD agents service is not being used 
- [x] ArgoCD service - heavily used for cluster and application provisioning and management
- [x] HashiCorp Vault - KMS for storing sensitive information integrated with OSC clusters via External Secret Operator. Used to manage credentials, certificates and etc.
- [x] Operate First GitHub organization and repositories - following GitOps approach majority of the OSC cluster configuration artifacts currently stored in repositories under Operate First Organization. While GitHub organization for now is not affected by changes , some of the artifacts will need to be migrated
- [x] GITHUB  org /code/PR management (Sesheta , Prow, Tide) 
- [x] Prow CI/CD pipeline to build jupyter images

**Comment by redmikhail** [comment]
**In Scope:** Identify all services that needs to be migrated based on priority . Migrate services and artifacts, achieve functional parity with Operate First managed platform.
**Out of Scope:** Re-architect , unless cannot be easily replicated, current approach to operational support and management.
**Implementation steps** (please update and link individual issues describing details for each step/task):

- [ ] Identify and review services and artifacts that needs to be migrated
- [ ] Provision/configure  cluster to host migrated services 
- [ ] Define Access Management process for migrated services 
- [ ] Create repositories for artifacts required for migrated services (example App of Apps for ArgoCD) 
- [ ] Provision ArgoCD cluster 
- [ ] Move ArgoCD OSC related applications from Operate First server as is 
- [ ] Provision/configure HashiCorp Vault , grant access 
- [ ] Migrate HashiCorp Vault secrets 
- [ ] OCM or RH ACM ?

**Comment by redmikhail** [comment]
@HeatherAck , @ryanaslett , @MightyNerdEric , @erikerlandson FYI . This is incomplete list of items,  please feel free to edit add anything that is required . Please note that implementation steps  meant to be as list of individual issues

**Comment by HeatherAck** [comment]
@erikerlandson, are there any items missing? "Identify and review services and artifacts that needs to be migrated"

**Comment by HeatherAck** [comment]
@cooktheryan will own the following items: 
- Provision ArgoCD cluster
- Move ArgoCD OSC related applications from Operate First server as is
- Provision/configure HashiCorp Vault , grant access
- Migrate HashiCorp Vault secrets

**Comment by HeatherAck** [comment]
@ryanaslett and @MightyNerdEric will own
- Define Access Management process for migrated services
- Create repositories for artifacts required for migrated services (example App of Apps for ArgoCD)

**Comment by HeatherAck** [comment]
Team decided to defer OCM, RH ACM until scale and complexity dictates it.

**Comment by HeatherAck** [comment]
@HeatherAck to create separate issues for items above

**Comment by HeatherAck** [comment]
@MightyNerdEric to troubleshoot the S3 issue so that prow functionality to be validated. (14-Apr)
