### ISSUE TITLE
EPIC: define end-to-end from data extraction to ITR analysis

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#324]
The Data Extraction team has reached the point where they can create rows of data for ITR from pdf reports.  This EPIC will answer how we intend the Data Extraction project to actually deliver that data as a data source for ITR.

Currently they can produce a CSV file in an S3 bucket, which can then be manually communicated to somebody who maintains an ITR data pipeline (and credentials necessary to access the data extraction S3 bucket), who can then ingest that CSV file to put data into Trino (using their own table-creation privileges), which can then be analyzed by the ITR tool (assuming the users have access to the necessary Trino tables).

Instead of managing shared storage via S3 credentials (and all the manual processes that entails), perhaps there is a better way to upload the data via Pachyderm, which can then feed into DBT, creating the necessary tables for ITR to add them as data sources for analysis.  This certainly assumes a level of user authorization within the Trino / Data Mesh world that is not yet Simple To Administer.

The purpose of this EPIC is to create a concrete recipe meeting that the Data Extraction and ITR teams can implement, while honoring the Data Mesh pattern and exemplifying good Data Governance practices.  Such a recipe can then be reviewed by the Data Mesh team and then we can publish the results as a demonstration milestone.

- [ ] Select 10-12 high-quality ESG reports containing all necessary or derive-able KPIs for ITR
- [ ] Verify that company names in ESG reports can map to LEIs and ISINs using Entity Matching
- [ ] Reference/connect financial/sector/region/currency datasets necessary to complete ITR data requirements.  (DERA for financial, OECD for currency.  Sector and Currency may come from PDF reports?)
- [ ] Describe how individual contributors (such as KPI producers and KPI consumers) register and gain permissions needed to work with data and each other (including how they publish / find data and each other)
- [ ] Please add additional workflow topics here!

CC: @HeatherAck @toki8 @caldeirav @ericbroda @ryanaslett @MightyNerdEric
